### ISSUE TITLE
where's the code?

### ISSUE THREAD

**Issue by xowii** [whoisnico/Billgang-Assist-Bot-Page#1]
hello where is the code?

**Comment by whoisnico** [comment]
At the end i did the code just working for my server. But i am adding the features on my new open src project.
https://github.com/whoisnico/echo-bot
I think i gonna finish it this weekend. Tell me if u want some features that you want ;)

**Comment by xowii** [comment]
Oh okay nice, it will be cool if you do a command like get-product and a required field with the order id and if the order id is correct then you receive a role in the discord server (and the order id can only be used 1 time to get the role if possible) I let you think for this idea ;) have a nice day

**Comment by whoisnico** [comment]
I would finish tommorow the customer role thing but the sellpass api doesnt work atm on orders request. So i think it will take some more time

**Comment by whoisnico** [comment]
New Public Bot is online
https://discord.com/api/oauth2/authorize?client_id=1208759133868662784&permissions=8&scope=bot+applications.commands
